In [3]:
import datetime as dt
from pandas import read_excel
from pandas import read_csv
from pandas import concat
from pandas import merge
import pandas as pd
import numpy as np
from pandas import Series
from pandas import DataFrame

import pymysql
from sqlalchemy import create_engine

In [4]:
HOSTNAME = 'izen.cxppaurfujpc.ap-northeast-2.rds.amazonaws.com'
PORT = 3306
USERNAME = 'admin'
PASSWORD = '1234567890'
DATABASE = 'project1'
CHARSET1 = 'utf8'
CHARSET2= 'utf-8'

In [5]:
con_str_fmt = 'mysql+mysqldb://{0}:{1}@{2}:{3}/{4}?charset={5}'
con_str = con_str_fmt.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE, CHARSET1)
con_str

'mysql+mysqldb://admin:1234567890@izen.cxppaurfujpc.ap-northeast-2.rds.amazonaws.com:3306/project1?charset=utf8'

In [6]:
pymysql.install_as_MySQLdb()
import MySQLdb

In [7]:
engine = create_engine(con_str, encoding=CHARSET2)
conn = engine.connect()

In [8]:
df = pd.read_sql_table('merge_table', index_col = 'index', con=conn)
df

,명칭(단지코드),사용승인일,동수 / 세대수,면적별 세대현황(전용면적 기준),연면적,주거전용면적,주차대수,CCTV대수,승강기대수,시공사 / 시행사,...,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
index,,,,,,,,,,,,,,,,,,,,,
0,LG개포자이아파트(A13593901),2004-06-17,4 / 212 세대,60㎡ 이하:\n- 세대\n60㎡ ~ 85㎡ 이하:\n- 세대\n85㎡ ~ 135㎡...,"60,358.78㎡","32,275.48㎡",지상: 19 / 지하: 483(총:502대),58.0,6,화엄건설 / LG건설,...,12.0,2.0,개포자이(12-2),134.30,202101.0,13.0,239500.0,8.0,2004.0,개포로109길69
1,LG개포자이아파트(A13593901),2004-06-17,4 / 212 세대,60㎡ 이하:\n- 세대\n60㎡ ~ 85㎡ 이하:\n- 세대\n85㎡ ~ 135㎡...,"60,358.78㎡","32,275.48㎡",지상: 19 / 지하: 483(총:502대),58.0,6,화엄건설 / LG건설,...,12.0,2.0,개포자이(12-2),134.30,202101.0,21.0,200000.0,13.0,2004.0,개포로109길69
2,LG개포자이아파트(A13593901),2004-06-17,4 / 212 세대,60㎡ 이하:\n- 세대\n60㎡ ~ 85㎡ 이하:\n- 세대\n85㎡ ~ 135㎡...,"60,358.78㎡","32,275.48㎡",지상: 19 / 지하: 483(총:502대),58.0,6,화엄건설 / LG건설,...,12.0,2.0,개포자이(12-2),170.32,202101.0,30.0,270000.0,19.0,2004.0,개포로109길69
3,LG개포자이아파트(A13593901),2004-06-17,4 / 212 세대,60㎡ 이하:\n- 세대\n60㎡ ~ 85㎡ 이하:\n- 세대\n85㎡ ~ 135㎡...,"60,358.78㎡","32,275.48㎡",지상: 19 / 지하: 483(총:502대),58.0,6,화엄건설 / LG건설,...,12.0,2.0,개포자이(12-2),153.80,202105.0,11.0,260000.0,21.0,2004.0,개포로109길69
4,LG개포자이아파트(A13593901),2004-06-17,4 / 212 세대,60㎡ 이하:\n- 세대\n60㎡ ~ 85㎡ 이하:\n- 세대\n85㎡ ~ 135㎡...,"60,358.78㎡","32,275.48㎡",지상: 19 / 지하: 483(총:502대),58.0,6,화엄건설 / LG건설,...,12.0,2.0,개포자이(12-2),134.30,202105.0,19.0,239850.0,6.0,2004.0,개포로109길69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20435,중화한신아파트(A13187702),1997-10-11,9 / 1544 세대,60㎡ 이하:\n892 세대\n60㎡ ~ 85㎡ 이하:\n652 세대\n85㎡ ~ ...,"144,301㎡","105,896.94㎡",지상: 475 / 지하: 1024(총:1499대),160.0,24,"한신공영 / 신천실업(주),청법지역주택외8개조합",...,450.0,0.0,한신2,59.76,202102.0,1.0,65000.0,8.0,1998.0,동일로752
20436,중화한신아파트(A13187702),1997-10-11,9 / 1544 세대,60㎡ 이하:\n892 세대\n60㎡ ~ 85㎡ 이하:\n652 세대\n85㎡ ~ ...,"144,301㎡","105,896.94㎡",지상: 475 / 지하: 1024(총:1499대),160.0,24,"한신공영 / 신천실업(주),청법지역주택외8개조합",...,450.0,0.0,한신2,84.03,202102.0,2.0,79800.0,6.0,1998.0,동일로752
20437,중화한신아파트(A13187702),1997-10-11,9 / 1544 세대,60㎡ 이하:\n892 세대\n60㎡ ~ 85㎡ 이하:\n652 세대\n85㎡ ~ ...,"144,301㎡","105,896.94㎡",지상: 475 / 지하: 1024(총:1499대),160.0,24,"한신공영 / 신천실업(주),청법지역주택외8개조합",...,450.0,0.0,한신2,59.76,202103.0,18.0,66500.0,14.0,1998.0,동일로752
20438,중화한신아파트(A13187702),1997-10-11,9 / 1544 세대,60㎡ 이하:\n892 세대\n60㎡ ~ 85㎡ 이하:\n652 세대\n85㎡ ~ ...,"144,301㎡","105,896.94㎡",지상: 475 / 지하: 1024(총:1499대),160.0,24,"한신공영 / 신천실업(주),청법지역주택외8개조합",...,450.0,0.0,한신2,59.76,202104.0,10.0,66000.0,6.0,1998.0,동일로752
20439,중화한신아파트(A13187702),1997-10-11,9 / 1544 세대,60㎡ 이하:\n892 세대\n60㎡ ~ 85㎡ 이하:\n652 세대\n85㎡ ~ ...,"144,301㎡","105,896.94㎡",지상: 475 / 지하: 1024(총:1499대),160.0,24,"한신공영 / 신천실업(주),청법지역주택외8개조합",...,450.0,0.0,한신2,59.76,202104.0,16.0,68000.0,13.0,1998.0,동일로752